# nnU-Net 环境配置
# 修改此文件后重新运行命令即生效；也可通过 run_nnunet.py --config 指定其它配置文件
nnUNet_raw: /home/xsy/pythoncode/xsy_datasets/nnUNet_data/nnUNet_raw
nnUNet_preprocessed: /home/xsy/pythoncode/xsy_datasets/nnUNet_data/nnUNet_preprocessed
nnUNet_results: /home/xsy/pythoncode/xsy_datasets/nnUNet_data/nnUNet_results

